[workspace]
members = [
    "simcore",
    "examples/*"
]
resolver = "2"

[profile.release-debug]
inherits = "release"
debug = true

[profile.release-optimized]
inherits = "release"
codegen-units = 1
lto = "fat"
