[graph]
all-features = true

[advisories]
ignore = [
]

[licenses]
allow = [
    "MIT",
    "Apache-2.0"
]
confidence-threshold = 0.8
exceptions = [
    { allow = ["Unicode-DFS-2016"], crate = "unicode-ident" },
    { allow = ["MPL-2.0"], crate = "colored" }
]

[bans]
multiple-versions = "deny"

[sources]
unknown-registry = "warn"
unknown-git = "warn"
