[package]
name = "intro-async"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
simcore = { path = "../..", features = ["async_mode"] }
serde = { version = "1", features = ["derive"] }
