[package]
name = "performance-example"
edition = "2021"
publish = false

[dependencies]
simcore = { path = "../.." }
clap = { version = "4", features = ["cargo", "derive"] }
env_logger = "0.11"
log = "0.4"
serde = { version = "1", features = ["derive"] }
sugars = "3"
