[package]
name = "intro-example"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
simcore = { path = "../..", features = ["async_mode"] }
serde = { version = "1.0", features = ["derive"] }
